import { Tag } from "antd";


export const RequestheaderColumns = [
  {
    title: 'Header Name',
    dataIndex: 'headerName',
    render: (text)=> <Tag color="geekblue">{text}</Tag>
  },
  {
    title: 'Header Value',
    dataIndex: 'headerValue',
  }
];



export const RequestHeaderdata = [
  {
    key: '1',
    headerName: 'Content-Type',
    headerValue: 'application/json',

  },
  {
    key: '2',
    headerName: 'X-AUTH',
    headerValue: `SHA256(base64 encoded payload + “/api/pg/sandbox/v1/pay/” + secret key) + **** + index`,
    
  }
];



export const RequestParameterdata = [
  {
    key: '1',
    parameterName: <small>merchantPublicKey</small>,
    dataType: 'STRING',
    description: `Unique merchantPublicKey assigned to the merchant by Itio
                    Note: merchantPublicKey length will be less than 38 characters.`,
    required: 'YES'
  },
  {
    key: '2',
    parameterName: <small>merchantSecretKey</small>,
    dataType: 'STRING',
    description: `Unique merchantSecretKey assigned to the merchant by Itio
                    Note: merchantSecretKey length will be less than 38 characters.`,
    required: 'YES'
  },
  {
    key: '3',
    parameterName: <small>merchantOrderId</small>,
    dataType: 'STRING',
    description: `Unique Order ID generated by the merchant to track request to Itio
                Note:
                - merchantOrderId length should be less than 35 characters
                - No Special characters allowed`,
    required: 'YES'
  },
  {
    key: '3',
    parameterName: <small>BusinessName</small>,
    dataType: 'STRING',
    description: `Business Name`,
    required: 'NO'
  },
  {
    key: '4',
    parameterName: <small>currency</small>,
    dataType: 'STRING',
    description: 'Default value USD',
    required: 'YES'
  },
  {
    key: '5',
    parameterName: <small>amount</small>,
    dataType: 'FLOAT',
    description: `Transaction amount in USD.
                Note: Amount should be greater than 100 (in Paise)`,
    required: 'YES'
  },
  {
    key: '6',
    parameterName: <small>redirectUrl</small>,
    dataType: 'STRING',
    description: 'The url where the user will be redirected after transaction completion.',
    required: 'YES'
  },
  {
    key: '7',
    parameterName: <small>callbackUrl</small>,
    dataType: 'STRING',
    description: `The url where server to server callback will be posted. Always POST.
                  This callback will be of POST type and will contain the same payload as the status response. 
                  The callback will contain an X-VERIFY header which the merchant should 
                  verify before decoding the response.`,
    required: 'YES'
  },
  {
    key: '8',
    parameterName: <small>mobileNumber</small>,
    dataType: 'STRING',
    description: `Mobile number of the user
                Note: There should not be any space.`,
    required: 'NO'
  },
  {
    key: '9',
    parameterName: <small>paymentInstrument</small>,
    dataType: 'OBJECT',
    description: 'Payment details',
    required: 'YES'
  },
  {
    key: '10',
    parameterName: <small>paymentInstrument.type</small>,
    dataType: 'ENUM',
    description: `Payment instrument type.
                Value will be: PAY_PAGE`,
    required: 'YES'
  },

];


export const sampleRequestPayload = `
{
  "merchantPublicKey": "PGTESTPAYUAT",
  "merchantSecretKey": "ewjuiyrtyuvghj567hjk",
  "merchantOrderId": "MT7850590068188104",
  "BusinessName": "XYZ Business",
  "currency": "USD",
  "amount": 10000,
  "redirectUrl": "https://webhook.site/redirect-url",
  "callbackUrl": "https://webhook.site/callback-url",
  "mobileNumber": "9999999999",
  "paymentInstrument": {
    "type": "PAY_PAGE"
  }
}
`;


export const sampleResponsePayload = `
{
    "success": true,
    "status": "PAYMENT_INITIATED",
    "message": "Payment Initiated",
    "data": {
        "merchantPublicKey": "1722830923-28TMTX6G89BI",
        "merchantOrderId": "eJxLdwQBp9xiNyfv5PJ4",
        "transactionID":  "JxLdwQBp9xiNyfv5PJ4dfghj567",
        "amount": 90,
        "currency": "USD",
        "instrumentResponse": {
            "type": "PAY_PAGE",
            "redirectInfo": {
                "url": "https://react-payment.oyefin.com/merchant/payment/checkout/?token=IjE3MjI4MzA5MjMtMjhUTVRYNkc4OUJJIg==,NC4w,ImFkNjIzYmY1ZWMwYzRlNmFhYmZlODY0YTQwMDM5NDY5MTkxIg==,IlVTRCI=",
            }
        }
    }
}`;


export const sampleRequestBase64EncodedPayload = `
{
  "request": "ewogICJtZXJjaGFudElkIjogIlBHVEVTVFBBWVVBVCIsCiAgIm1lcmNoYW50VHJhbnNhY3Rpb25JZCI6ICJNVDc4NTA1OTAwNjgxODgxMDQiLAogICJtZXJjaGFudFVzZXJJZCI6ICJNVUlEMTIzIiwKICAiYW1vdW50IjogMTAwMDAsCiAgInJlZGlyZWN0VXJsIjogImh0dHBzOi8vd2ViaG9vay5zaXRlL3JlZGlyZWN0LXVybCIsCiAgInJlZGlyZWN0TW9kZSI6ICJSRURJUkVDVCIsCiAgImNhbGxiYWNrVXJsIjogImh0dHBzOi8vd2ViaG9vay5zaXRlL2NhbGxiYWNrLXVybCIsCiAgIm1vYmlsZU51bWJlciI6ICI5OTk5OTk5OTk5IiwKICAicGF5bWVudEluc3RydW1lbnQiOiB7CiAgICAidHlwZSI6ICJQQVlfUEFHRSIKICB9Cn0=",
}
`;



export const RequestParameterColumns = [
  {
    title: 'Parameter Name',
    dataIndex: 'parameterName',
    width: 180,
    render: (text)=> (<Tag color='geekblue'>{text}</Tag>)
  },
  {
    title: 'Data Type',
    dataIndex: 'dataType',
    width: 100,
    render: (text)=> (<Tag color='geekblue'>{text}</Tag>)
  },
  {
    title: 'Description',
    dataIndex: 'description',
    width: 380
  },
  {
    title: 'Required',
    dataIndex: 'required',
    render: (text)=> (<Tag color='geekblue'>{text}</Tag>)
  },
];



export const ResponseHeaderTable = [
    {
        title: 'Header Name',
        dataIndex: 'headerName',
        render: (text)=> (<Tag color="geekblue">{text}</Tag>)
      },
    {
        title: 'Header Value',
        dataIndex: 'headerValue',
      },
]


export const ResponseHeaderTabledata = [
    {
        key: '1',
        headerName: 'Content-Type',
        headerValue: 'application/json',
      },
];


export const ResponseParameterColumn = [
    {
        title: 'Parameter Name',
        dataIndex: 'parameterName',
        width: 180,
        render: (text)=> (<Tag color="geekblue">{text}</Tag>)
      },
      {
        title: 'Data Type',
        dataIndex: 'dataType',
        width: 100,
        render: (text)=> (<Tag color="geekblue">{text}</Tag>)
      },
      {
        title: 'Description',
        dataIndex: 'description',
        width: 380
      }
]




export const ResponseParameterTabledata = [
    {
      key: '1',
      parameterName: <small>success</small>,
      dataType: 'boolean',
      description: `Success/failure of request processing`,
    },
    {
      key: '2',
      parameterName: <small>status</small>,
      dataType: 'STRING',
      description: `Payment Status`,
    },
    {
      key: '3',
      parameterName: <small>message</small>,
      dataType: 'STRING',
      description: `Additional Information related to Transaction`,
    },
    {
      key: '4',
      parameterName: <small>merchantPublicKey</small>,
      dataType: 'STRING',
      description: 'Merchant Public URL provided by Itio',
    },
    {
      key: '5',
      parameterName: <small>merchantOrderId</small>,
      dataType: 'STRING',
      description: `Order ID provided by merchant during payment`,
    },
    {
      key: '6',
      parameterName: <small>transactionID</small>,
      dataType: 'STRING',
      description: 'Unique Transaction ID created for the transaction',
    },
    {
      key: '7',
      parameterName: <small>amount</small>,
      dataType: 'FLOAT',
      description: `Transaction Amount`,
    },
    {
      key: '8',
      parameterName: <small>currency</small>,
      dataType: 'STRING',
      description: `Transaction Currency`,
    },
    {
      key: '9',
      parameterName: <small>redirectInfo</small>,
      dataType: 'OBJECT',
      description: 'Payload for redirecting user to bank page for authentications',
    },
    {
      key: '10',
      parameterName: <small>url</small>,
      dataType: 'STRING',
      description: `Url on which user needs to be redirected for authentication`,
    }
  ];


export const CallbackHeaderColumn = [
    {
        title: 'Header Name',
        dataIndex: 'headerName',
        render: (text)=> (<Tag color="geekblue">{text}</Tag>)
      },
      {
        title: 'Header Value',
        dataIndex: 'headerValue',
      }
];



export const CallbackTableData = [
    {
        key: '1',
        headerName: 'Content-Type',
        headerValue: 'application/json'
      },
    //   {
    //     key: '2',
    //     headerName: 'X-AUTH',
    //     headerValue: `SHA256(base64 encoded payload + “/api/pg/sandbox/v1/pay/” + secret key) + **** + index`
    //   }
];

export const sampleCallbackURLResponse = 
    {
        "response": "ewogICJzdWNjZXNzIjogdHJ1ZSwKICAiY29kZSI6ICJQQVlNRU5UX1NVQ0NFU1MiLAogICJtZXNzYWdlIjogIllvdXIgcmVxdWVzdCBoYXMgYmVlbiBzdWNjZXNzZnVsbHkgY29tcGxldGVkLiIsCiAgImRhdGEiOiB7CiAgICAibWVyY2hhbnRJZCI6ICJQR1RFU1RQQVlVQVQiLAogICAgIm1lcmNoYW50VHJhbnNhY3Rpb25JZCI6ICJNVDc4NTA1OTAwNjgxODgxMDQiLAogICAgInRyYW5zYWN0aW9uSWQiOiAiVDIxMTEyMjE0Mzc0NTYxOTAxNzAzNzkiLAogICAgImFtb3VudCI6IDEwMCwKICAgICJzdGF0ZSI6ICJDT01QTEVURUQiLAogICAgInJlc3BvbnNlQ29kZSI6ICJTVUNDRVNTIiwKICAgICJwYXltZW50SW5zdHJ1bWVudCI6IHGUiOiAiVVBJIiwKICAgICAgInV0ciI6ICIyMDYzNzg4NjYxMTIiCiAgICB9CiAgfQp9Cg=="
};



export const Base64DecodedCallbackResponse = 
    {
        "success": true,
        "code": "PAYMENT_SUCCESS",
        "message": "Your payment has been successful",
        "data": {
          "merchantPublicKey": "PGTESTPAYUAT",
          "merchantOrderId": "MT7850590068188104",
          "transactionID": "T2111221437456190170379",
          "amount": 100,
          "currency": "USD",
          "paymentInstrument": {
            "type": "Card",
          }
        }
  };




export const CheckStatusRequestHeaderTableData = [
  {
    key: '1',
    headerName: 'Content-Type',
    headerValue: 'application/json'
  },
];


export const CheckStatusPathParametersColumn = [
  {
    title: 'Parameter Name',
    dataIndex: 'parameterName',
    render: (text)=> <Tag color="geekblue">{text}</Tag>
  },
  {
    title: 'Type',
    dataIndex: 'type',
    render: (text)=> <Tag color="geekblue">{text}</Tag>
  },
  {
    title: 'Description',
    dataIndex: 'description',
  },
  {
    title: 'Mandatory',
    dataIndex: 'mandatory',
    render: (text)=> <Tag color="geekblue">{text}</Tag>
  }
];



export const CheckStatusPathParametersTableData = [
    {
      parameterName: 'merchantPublicKey',
      type: 'STRING',
      description: 'Public Key assigned to the Merchant by Itio',
      mandatory: 'Yes'
    },
    {
      parameterName: 'merchantOrderID',
      type: 'STRING',
      description: 'Unique Order ID Provided by Merchant during transaction',
      mandatory: 'Yes'
    }
];


export const CheckStatusSampleSuccessResponse = `{
      "success": true,
      "status": "PAYMENT_SUCCESS",
      "message": "Your request has been successfully completed.",
      "data": {
        "merchantPublicKey": "PGTESTPAYUAT",
        "merchantOrderId": "MT7850590068188104",
        "transactionID": "T2111221437456190170379",
        "amount": 100,
        "currency": "USD",
        "paymentInstrument": {
          "type": "Card",
        }
      }
}`

export const CheckStatusSampleFailResponse = `
{
    "success": false,
    "status": "PAYMENT_FAILED"
    "message": "There is an error trying to process your transaction at the moment. Please try again in a while."
}`

